use crate::{
  cli::Arguments,
  project::Directory,
  shared_files as files,
  transaction::{Change, Transaction},
};
use anyhow::{bail, Result};
use serde::{Deserialize, Serialize};
use serde_json::{json, Value};
use std::{
  collections::{BTreeMap, BTreeSet},
  fs,
  io::Read,
  path::{Path, PathBuf},
};

pub(crate) const COMMANDS: &[&str] = &["--list", "--save", "--add", "--sync", "--remove"];
#[derive(Clone, Deserialize, Serialize)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub(crate) struct SharedFile {
  path: String,
  sha256: String,
}
#[derive(Clone, Deserialize, Serialize)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub(crate) struct SharedTask {
  pub id: String,
  entry_point: String,
  pub description: String,
  runtime: String,
  files: Vec<SharedFile>,
  requires: Vec<String>,
}
impl SharedTask {
  fn revision(&self) -> String {
    files::hash(files::dotnet_json(&serde_json::to_value(self).unwrap()).as_bytes())
  }
}
#[derive(Deserialize, Serialize)]
#[serde(deny_unknown_fields)]
struct SharedCatalog {
  version: i32,
  tasks: Vec<SharedTask>,
}
#[derive(Clone, Deserialize, Serialize)]
#[serde(deny_unknown_fields)]
struct Installed {
  source: String,
  revision: String,
  requires: Vec<String>,
  files: BTreeMap<String, String>,
}
impl Installed {
  fn from(source: &str, task: &SharedTask) -> Self {
    Self {
      source: source.into(),
      revision: task.revision(),
      requires: task.requires.iter().map(|s| format!("{source}/{s}")).collect(),
      files: task
        .files
        .iter()
        .map(|f| (format!("{source}/{}", f.path), f.sha256.clone()))
        .collect(),
    }
  }
}
#[derive(Clone, Deserialize, Serialize)]
#[serde(deny_unknown_fields)]
pub(crate) struct Tracking {
  version: i32,
  directory: String,
  tasks: BTreeMap<String, Installed>,
}
impl Tracking {
  pub fn read(bytes: Option<&[u8]>, prefix: &str) -> Result<Self> {
    let Some(bytes) = bytes else {
      return Ok(Self {
        version: 1,
        directory: prefix.into(),
        tasks: BTreeMap::new(),
      });
    };
    let tracking: Self =
      serde_json::from_value(crate::yaml::parse(std::str::from_utf8(bytes)?, ".dotasks-lock.yaml")?)?;
    if tracking.version != 1 || tracking.directory != prefix {
      bail!("The shared task lock has an unsupported version or belongs to a different task directory.");
    }
    let mut ids = BTreeSet::new();
    let mut paths = BTreeMap::new();
    for (id, task) in &tracking.tasks {
      files::id(id, 3)?;
      if !ids.insert(id.to_lowercase())
        || task.source != id.split('/').next().unwrap()
        || !files::is_hash(&task.revision)
        || task.files.is_empty()
      {
        bail!("Invalid tracking entry '{id}'.");
      }
      for dependency in &task.requires {
        files::id(dependency, 3)?;
      }
      for (path, hash) in &task.files {
        files::relative(path)?;
        if !path.starts_with(&format!("{}/", task.source))
          || !files::is_hash(hash)
          || paths
            .insert(path.to_lowercase(), (path, hash))
            .is_some_and(|p| p != (path, hash))
        {
          bail!("Invalid or conflicting tracked file '{path}'.");
        }
      }
      if !task.files.contains_key(&format!("{id}.cs")) {
        bail!("Missing entry point tracking for '{id}'.");
      }
    }
    Ok(tracking)
  }
  fn serialize(&self) -> Result<Vec<u8>> {
    // JSON is valid YAML; keep the readable YAML form used by the reference CLI.
    let mut s = format!(
      "# Generated by dotask. Commit this file with your project tasks.\nversion: 1\ndirectory: {}\ntasks:{}\n",
      self.directory,
      if self.tasks.is_empty() { " {}" } else { "" }
    );
    for (id, task) in &self.tasks {
      s += &format!(
        "  {id}:\n    source: {}\n    revision: {}\n    requires:{}\n",
        task.source,
        task.revision,
        if task.requires.is_empty() { " []" } else { "" }
      );
      for r in &task.requires {
        s += &format!("    - {r}\n");
      }
      s += "    files:\n";
      for (path, hash) in &task.files {
        s += &format!("      {path}: {hash}\n");
      }
    }
    Ok(s.into_bytes())
  }
  fn file_map(&self) -> BTreeMap<String, String> {
    self.tasks.values().flat_map(|t| t.files.clone()).collect()
  }
  pub fn ids(&self) -> impl Iterator<Item = &String> {
    self.tasks.keys()
  }
}

#[derive(Clone)]
struct Selection {
  source: String,
  pattern: String,
}
impl Selection {
  fn parse(args: &[String]) -> Result<Vec<Self>> {
    let mut out = vec![];
    for arg in args {
      if let Some(open) = arg.find('{') {
        if !arg.ends_with('}') || open == 0 || !arg[..open].ends_with('/') || arg[open + 1..arg.len() - 1].contains('{')
        {
          bail!("Invalid task selection '{arg}'. Use \"dotnet/{{build,run,format}}\".");
        }
        let members: Vec<_> = arg[open + 1..arg.len() - 1].split(',').collect();
        if members.iter().any(|m| m.is_empty() || m.contains(['/', '*'])) {
          bail!("Invalid task selection '{arg}'.");
        }
        out.extend(Self::parse(
          &members.iter().map(|m| format!("{}{m}", &arg[..open])).collect::<Vec<_>>(),
        )?);
        continue;
      }
      let segments: Vec<_> = arg.split('/').collect();
      let explicit = segments.len() == 3
        || segments.len() == 2 && ["_", "private-tasks"].contains(&segments[0].to_lowercase().as_str());
      let source = if explicit {
        segments[0].to_lowercase()
      } else {
        "_".into()
      };
      let pattern = if explicit {
        segments[1..].join("/")
      } else {
        arg.clone()
      };
      files::id(&source, 1)?;
      if pattern != "*" {
        if let Some(group) = pattern.strip_suffix("/*") {
          files::id(group, 1)?;
        } else {
          files::id(&pattern, 2)?;
        }
      }
      out.push(Self { source, pattern });
    }
    Ok(out)
  }
  fn matches(&self, id: &str) -> bool {
    self.pattern == "*"
      || if let Some(prefix) = self.pattern.strip_suffix('*') {
        id.to_lowercase().starts_with(&prefix.to_lowercase())
      } else {
        id.eq_ignore_ascii_case(&self.pattern)
      }
  }
}
pub(crate) struct Store {
  pub cache: PathBuf,
  private: PathBuf,
  online: Option<PathBuf>,
}
impl Store {
  pub fn environment() -> Result<Self> {
    let home = std::env::var_os(if cfg!(windows) { "USERPROFILE" } else { "HOME" })
      .map(PathBuf::from)
      .ok_or_else(|| anyhow::anyhow!("User home directory is unavailable."))?;
    let env_path = |name: &str, fallback: PathBuf| -> Result<PathBuf> {
      let path = std::env::var_os(name).map(PathBuf::from).unwrap_or(fallback);
      crate::project::portable_path(&std::env::current_dir()?, &path.to_string_lossy())
    };
    let cache = if cfg!(windows) {
      env_path("LOCALAPPDATA", home.join("AppData/Local"))?.join("dotask/tasks")
    } else if cfg!(target_os = "macos") {
      home.join("Library/Caches/dotask/tasks")
    } else {
      env_path("XDG_CACHE_HOME", home.join(".cache"))?.join("dotask/tasks")
    };
    let config = if cfg!(windows) {
      env_path("APPDATA", home.join("AppData/Roaming"))?
    } else {
      env_path("XDG_CONFIG_HOME", home.join(".config"))?
    };
    Ok(Self {
      cache: env_path("DOTASK_CACHE_HOME", cache)?,
      private: env_path("DOTASK_PRIVATE_TASKS", config.join("dotask/private-tasks"))?,
      online: std::env::var_os("DOTASK_ONLINE_TASKS").map(PathBuf::from),
    })
  }
  fn catalog(&self, source: &str, refresh: bool) -> Result<SharedCatalog> {
    if source == "private-tasks" {
      return self.private_catalog();
    }
    if source != "_" {
      bail!("Unknown shared task source '{source}'. This version supports _ and private-tasks; additional repositories are deferred.");
    }
    let cache = files::resolve(&self.cache, "_/catalog.json")?;
    let bytes = if !refresh && cache.is_file() {
      fs::read(&cache)?
    } else {
      self.online("catalog.json")?
    };
    let catalog: SharedCatalog = serde_json::from_slice(&bytes)?;
    validate_catalog(&catalog)?;
    if refresh || !cache.is_file() {
      files::private_directory(&self.cache)?;
      files::atomic(&cache, &bytes, true)?;
    }
    Ok(catalog)
  }
  fn private_catalog(&self) -> Result<SharedCatalog> {
    if !self.private.is_dir() {
      return Ok(SharedCatalog {
        version: 1,
        tasks: vec![],
      });
    }
    files::check_link(&self.private)?;
    let paths = crate::catalog::sources(&self.private, false, false)?;
    let targets: Vec<_> = paths.iter().map(|p| crate::task_metadata::metadata(p, &self.private)).collect();
    let mut tasks = vec![];
    for target in targets {
      let relative = target
        .file_path
        .strip_prefix(&self.private)?
        .to_string_lossy()
        .replace('\\', "/");
      let id = relative[..relative.len() - 3].to_owned();
      files::id(&id, 2)?;
      let manifest = target.file_path.with_extension("task.json");
      files::check_link(&manifest)?;
      if manifest.is_file() {
        bail!(
          "Move '{}' into task/file requirements in the YAML header in '{}', then remove the .task.json file.",
          manifest.display(),
          target.file_path.display()
        );
      }
      if let Some(error) = target.error {
        bail!("{relative}: {error}");
      }
      let mut paths = BTreeSet::from([relative.clone()]);
      let mut requires = vec![];
      for r in target.metadata["Requirements"].as_array().into_iter().flatten() {
        if r["Kind"] == "file" {
          paths.insert(r["Value"].as_str().unwrap().into());
        }
        if r["Kind"] == "task" {
          requires.push(r["Value"].as_str().unwrap().into());
        }
      }
      let assets = paths
        .into_iter()
        .map(|p| {
          let source = files::resolve(&self.private, &p)?;
          Ok(SharedFile {
            path: p,
            sha256: files::hash_file(&source)?
              .ok_or_else(|| anyhow::anyhow!("Missing private task support file: {}", source.display()))?,
          })
        })
        .collect::<Result<_>>()?;
      tasks.push(SharedTask {
        id,
        entry_point: relative,
        description: target.description,
        runtime: "csharp".into(),
        files: assets,
        requires,
      });
    }
    let catalog = SharedCatalog { version: 1, tasks };
    validate_catalog(&catalog)?;
    Ok(catalog)
  }
  pub fn cached(&self) -> Result<Vec<(String, String)>> {
    let mut entries = vec![];
    let path = files::resolve(&self.cache, "_/catalog.json")?;
    if path.is_file() {
      let catalog: SharedCatalog = serde_json::from_slice(&fs::read(path)?)?;
      validate_catalog(&catalog)?;
      for t in catalog.tasks {
        entries.push((format!("_/{}", t.id), t.description.clone()));
        entries.push((t.id, t.description));
      }
    }
    // Private completion reads only metadata; it never hashes/copies support files.
    let paths = crate::catalog::sources(&self.private, false, false)?;
    if !paths.is_empty() {
      let targets: Vec<_> = paths.iter().map(|p| crate::task_metadata::metadata(p, &self.private)).collect();
      for t in targets {
        let id = t
          .file_path
          .strip_prefix(&self.private)?
          .with_extension("")
          .to_string_lossy()
          .replace('\\', "/");
        if files::id(&id, 2).is_ok() {
          entries.push((format!("private-tasks/{id}"), t.description));
        }
      }
    }
    Ok(entries)
  }
  fn online(&self, relative: &str) -> Result<Vec<u8>> {
    files::relative(relative)?;
    if let Some(root) = &self.online {
      if !root.is_absolute() {
        bail!("DOTASK_ONLINE_TASKS must be an absolute local directory containing catalog.json (for preview/publisher testing).");
      }
      return Ok(fs::read(files::resolve(root, relative)?)?);
    }
    let relative = relative.replace(' ', "%20");
    // The network worker owns the response. The foreground remains cancellable
    // even during DNS/TLS; exiting drops the worker without project mutations.
    let (sender, receiver) = std::sync::mpsc::sync_channel(1);
    std::thread::spawn(move || {
      let read = (|| -> Result<Vec<u8>> {
        let agent = ureq::Agent::new_with_config(
          ureq::Agent::config_builder()
            .https_only(true)
            .timeout_global(Some(std::time::Duration::from_secs(30)))
            .build(),
        );
        let mut response = agent
          .get(format!(
            "https://raw.githubusercontent.com/kodybrown/dotask/main/shared-tasks/{relative}"
          ))
          .call()?;
        let mut bytes = vec![];
        response
          .body_mut()
          .as_reader()
          .take(16 * 1024 * 1024 + 1)
          .read_to_end(&mut bytes)?;
        if bytes.len() > 16 * 1024 * 1024 {
          bail!("Shared task download exceeds the 16 MiB per-file limit.");
        }
        Ok(bytes)
      })();
      let _ = sender.send(read);
    });
    loop {
      crate::process::check_cancelled()?;
      match receiver.recv_timeout(std::time::Duration::from_millis(50)) {
        Ok(result) => return result,
        Err(std::sync::mpsc::RecvTimeoutError::Timeout) => {}
        Err(e) => return Err(e.into()),
      }
    }
  }
  fn object(&self, source: &str, hash: &str) -> Result<PathBuf> {
    files::id(source, 1)?;
    if !files::is_hash(hash) {
      bail!("Invalid snapshot hash.");
    }
    files::resolve(&self.cache, &format!("{source}/.objects/{hash}"))
  }
  fn original(&self, source: &str, hash: &str) -> Result<Vec<u8>> {
    let bytes = fs::read(self.object(source, hash)?)?;
    if files::hash(&bytes) != hash {
      bail!("A local cache snapshot failed its SHA-256 check. Project files are preserved.");
    }
    Ok(bytes)
  }
  fn save(&self, source: &str, task: &SharedTask) -> Result<()> {
    files::private_directory(&self.cache)?;
    for file in &task.files {
      crate::process::check_cancelled()?;
      let object = self.object(source, &file.sha256)?;
      let bytes = if files::hash_file(&object)?.as_deref() == Some(&file.sha256) {
        fs::read(&object)?
      } else {
        let bytes = if source == "private-tasks" {
          fs::read(files::resolve(&self.private, &file.path)?)?
        } else {
          self.online(&file.path)?
        };
        if files::hash(&bytes) != file.sha256 {
          bail!("Shared task '{source}/{}' changed during download or failed SHA-256 verification ({}). Retry --sync/--save; project files have not been changed.",task.id,file.path);
        }
        files::atomic(&object, &bytes, true)?;
        bytes
      };
      if source != "private-tasks" {
        files::atomic(&files::resolve(&self.cache, &format!("{source}/{}", file.path))?, &bytes, true)?;
      }
    }
    files::atomic(
      &files::resolve(&self.cache, &format!("{source}/.revisions/{}.json", task.revision()))?,
      files::dotnet_json(&serde_json::to_value(task)?).as_bytes(),
      true,
    )
  }
  fn select(
    &self,
    selections: &[Selection],
    refresh: bool,
    dependencies: bool,
  ) -> Result<BTreeMap<String, SharedTask>> {
    let mut result = BTreeMap::new();
    for source in selections.iter().map(|s| &s.source).collect::<BTreeSet<_>>() {
      let catalog = self.catalog(source, refresh)?;
      fn add(
        result: &mut BTreeMap<String, SharedTask>,
        task: &SharedTask,
        catalog: &SharedCatalog,
        source: &str,
        dependencies: bool,
        visiting: &mut BTreeSet<String>,
      ) -> Result<()> {
        let id = format!("{source}/{}", task.id);
        if !visiting.insert(id.to_lowercase()) {
          bail!("Shared task dependency cycle at '{id}'.");
        }
        if !result.contains_key(&id) {
          if dependencies {
            for required in &task.requires {
              let t = catalog.tasks.iter().find(|t| t.id.eq_ignore_ascii_case(required)).unwrap();
              add(result, t, catalog, source, dependencies, visiting)?;
            }
          }
          result.insert(id.clone(), task.clone());
        }
        visiting.remove(&id.to_lowercase());
        Ok(())
      }
      for selection in selections.iter().filter(|s| &s.source == source) {
        let matches: Vec<_> = catalog.tasks.iter().filter(|t| selection.matches(&t.id)).collect();
        if matches.is_empty() && selection.pattern != "*" {
          bail!(
            "No shared tasks match '{source}/{}'. Existing project files are preserved.",
            selection.pattern
          );
        }
        for t in matches {
          add(&mut result, t, &catalog, source, dependencies, &mut BTreeSet::new())?;
        }
      }
    }
    Ok(result)
  }
}
fn validate_catalog(catalog: &SharedCatalog) -> Result<()> {
  if catalog.version != 1 || catalog.tasks.len() > 10000 {
    bail!("Unsupported or invalid shared task catalog.");
  }
  let mut ids = BTreeSet::new();
  let mut all = BTreeMap::new();
  for t in &catalog.tasks {
    files::id(&t.id, 2)?;
    if !ids.insert(t.id.to_lowercase())
      || t.runtime != "csharp"
      || t.entry_point != format!("{}.cs", t.id)
      || t.files.is_empty()
      || t.files.len() > 128
    {
      bail!(
        "Invalid or unsupported shared task '{}'. Only C# tasks are supported in this version.",
        t.id
      );
    }
    let mut paths = BTreeSet::new();
    for f in &t.files {
      files::relative(&f.path)?;
      let parts: Vec<_> = f.path.split('/').collect();
      if !paths.insert(f.path.to_lowercase())
        || !files::is_hash(&f.sha256)
        || parts.len() < 2
        || parts.iter().any(|p| p.starts_with('.'))
        || f.path.to_lowercase().ends_with(".cs")
          && f.path != t.entry_point
          && !parts[..parts.len() - 1].iter().any(|p| p.starts_with('_'))
      {
        bail!(
          "Invalid file '{}' in shared task '{}'. C# support files must be inside an _support directory.",
          f.path,
          t.id
        );
      }
      if all
        .insert(f.path.to_lowercase(), (&f.path, &f.sha256))
        .is_some_and(|p| p != (&f.path, &f.sha256))
      {
        bail!("Conflicting file definitions for '{}' in the online catalog.", f.path);
      }
    }
    if !paths.contains(&t.entry_point.to_lowercase()) {
      bail!("Missing entry point file for '{}'.", t.id);
    }
    for r in &t.requires {
      files::id(r, 2)?;
    }
  }
  for t in &catalog.tasks {
    for r in &t.requires {
      if !ids.contains(&r.to_lowercase()) {
        bail!("Shared task '{}' requires missing task '{r}'.", t.id);
      }
    }
  }
  Ok(())
}

pub(crate) fn run(command: &Arguments) -> Result<i32> {
  let action = command.remaining[0].to_lowercase();
  let args = &command.remaining[1..];
  let dry = args.iter().any(|a| a.eq_ignore_ascii_case("--dry-run"));
  let accept = args.iter().any(|a| a.eq_ignore_ascii_case("--accept-merge"));
  let args: Vec<_> = args
    .iter()
    .filter(|a| !a.eq_ignore_ascii_case("--dry-run") && !a.eq_ignore_ascii_case("--accept-merge"))
    .cloned()
    .collect();
  if args.iter().any(|a| a.starts_with('-'))
    || dry && !["--add", "--sync", "--remove"].contains(&action.as_str())
    || accept && (action != "--sync" || args.is_empty())
  {
    bail!("Usage: dotask --list [SELECTION...] | --save SELECTION... | --add SELECTION... [--dry-run] | --sync [SELECTION...] [--dry-run] [--accept-merge] | --remove SELECTION... [--dry-run]");
  }
  if args.is_empty() && ["--add", "--save", "--remove"].contains(&action.as_str()) {
    bail!("{action} requires a task selection, for example dotnet/build or \"dotnet/{{build,run}}\".");
  }
  let mut selections = Selection::parse(&if args.is_empty() && action == "--list" {
    vec!["*".into()]
  } else {
    args
  })?;
  if accept && selections.iter().any(|s| s.pattern.contains('*')) {
    bail!("--accept-merge requires explicitly named tasks, without wildcards.");
  }
  let invocation = std::env::current_dir()?;
  if command.verbose {
    eprintln!("[dotask] Shared-task command: {action}; invocation: {}", invocation.display());
  }
  let store = Store::environment()?;
  if action == "--list" || action == "--save" {
    let tasks = store.select(&selections, true, action == "--save")?;
    if action == "--list" && !tasks.is_empty() {
      listing(&store, &tasks, &invocation, command.use_directory.as_deref())?;
    }
    if action == "--save" {
      for (id, task) in &tasks {
        store.save(id.split('/').next().unwrap(), task)?;
        println!("Saved {id}");
      }
    }
    if tasks.is_empty() {
      println!("No shared tasks found.");
    }
    return Ok(0);
  }
  let project = Directory::locate_optional(invocation, command.use_directory.as_deref(), action == "--add")?;
  let prefix = project
    .task_directory
    .strip_prefix(&project.root_directory)
    .map_err(|_| anyhow::anyhow!("Shared project tasks must be in a subdirectory of the project root."))?
    .to_string_lossy()
    .replace('\\', "/");
  files::relative(&prefix)?;
  files::resolve(&project.root_directory, &prefix)?;
  let transaction = Transaction {
    project: &project,
    prefix: prefix.clone(),
  };
  let _lease = transaction.acquire(&store.cache)?;
  if transaction.pending()? {
    if dry {
      bail!(
        "An interrupted update requires recovery. Run the management command without --dry-run to recover it first."
      );
    }
    transaction.recover()?;
    println!("Recovered the interrupted shared-task operation.");
  }
  crate::configuration::load(&project)?;
  let lock = files::resolve(&project.root_directory, ".dotasks-lock.yaml")?;
  let before_bytes = if lock.is_file() {
    Some(fs::read(&lock)?)
  } else {
    None
  };
  let before = Tracking::read(before_bytes.as_deref(), &prefix)?;
  let mut next = before.clone();
  let mut preserve = BTreeSet::new();
  let mut conflicts = vec![];
  if action == "--remove" {
    for id in installed(&before, &selections)? {
      verify_installed(&project, &before.tasks[&id], &mut conflicts)?;
      next.tasks.remove(&id);
      println!("{} {id}", if dry { "Would remove" } else { "Remove" });
    }
  } else {
    if action == "--sync" {
      let ids = if selections.is_empty() {
        before.tasks.keys().cloned().collect()
      } else {
        installed(&before, &selections)?
      };
      selections = Selection::parse(&ids)?;
    }
    for (id, task) in store.select(&selections, action == "--sync", true)? {
      let source = id.split('/').next().unwrap();
      if action == "--add"
        && let Some(already) = before.tasks.get(&id)
      {
        verify_installed(&project, already, &mut conflicts)?;
        println!("Already installed: {id}. Use --sync to update it.");
        continue;
      }
      store.save(source, &task)?;
      let replacement = Installed::from(source, &task);
      if let Some(installed) = before.tasks.get(&id) {
        let mut changed = vec![];
        for (path, hash) in &installed.files {
          let path = files::resolve(&project.task_directory, path)?;
          if files::hash_file(&path)?.as_ref() != Some(hash) {
            changed.push(path);
          }
        }
        if installed.revision == replacement.revision {
          for path in &changed {
            if !path.is_file() {
              conflicts.push(format!(
                "Tracked file is missing: {}. Restore it explicitly; sync will not undo a local deletion.",
                path.display()
              ));
            }
          }
          println!(
            "Unchanged: {id}{}",
            if changed.is_empty() {
              ""
            } else {
              " (local changes preserved)"
            }
          );
          continue;
        }
        let same = installed.files.keys().eq(replacement.files.keys());
        let mut matches = same;
        for (path, hash) in &replacement.files {
          matches &= files::hash_file(&files::resolve(&project.task_directory, path)?)?.as_ref() == Some(hash);
        }
        if !changed.is_empty() && !matches {
          let selected = accept
            && selections
              .iter()
              .any(|s| s.source == source && s.pattern.eq_ignore_ascii_case(&task.id));
          let review = review_path(&store, &project, &id, &replacement.revision)?;
          let expected = json!({"task":id,"beforeRevision":installed.revision,"incomingRevision":replacement.revision});
          let reviewed = fs::read(review.join("review.json"))
            .ok()
            .and_then(|b| serde_json::from_slice::<Value>(&b).ok())
            .is_some_and(|v| v == expected);
          let existing = installed
            .files
            .keys()
            .map(|p| files::resolve(&project.task_directory, p))
            .collect::<Result<Vec<_>>>()?
            .iter()
            .all(|p| p.is_file());
          if selected && same && reviewed && existing {
            preserve.extend(installed.files.keys().cloned());
            println!("Record reviewed merge: {id}. Local differences remain protected.");
          } else {
            comparison(&store, &project, &review, installed, &replacement, &expected)?;
            conflicts.push(format!("Locally modified: {id}. Files were preserved. Compare originals/project/incoming in {}. Merge manually, then run dotask --sync {id} --accept-merge; or replace the project copy with incoming and rerun --sync.",review.display()));
            continue;
          }
        }
      }
      next.tasks.insert(id.clone(), replacement);
      println!(
        "{} {id}",
        if dry {
          "Would install/update"
        } else {
          "Install/update"
        }
      );
    }
  }
  for (id, task) in &next.tasks {
    for required in &task.requires {
      if !next.tasks.contains_key(required) {
        conflicts.push(format!("Cannot remove required task '{required}'; '{id}' still depends on it."));
      }
    }
  }
  let after_bytes = next.serialize()?;
  Tracking::read(Some(&after_bytes), &prefix)?;
  let old_files = before.file_map();
  let new_files = next.file_map();
  let mut changes = vec![];
  for path in old_files.keys().chain(new_files.keys()).collect::<BTreeSet<_>>() {
    let old = old_files.get(path);
    let new = new_files.get(path);
    if old == new || preserve.contains(path) {
      continue;
    }
    let destination = files::resolve(&project.task_directory, path)?;
    let current = files::hash_file(&destination)?;
    if destination.is_dir()
      || old.is_none() && current.is_some()
      || old.is_some() && current.as_ref() != old && (current.is_none() || current.as_ref() != new)
    {
      conflicts.push(format!(
        "Refusing to overwrite/remove '{}': it is untracked, missing, or locally modified.",
        destination.display()
      ));
      continue;
    }
    if current.as_ref() != new {
      changes.push(Change {
        path: format!("{prefix}/{path}"),
        before: current,
        after: new
          .map(|hash| store.original(path.split('/').next().unwrap(), hash))
          .transpose()?,
      });
    }
  }
  if !conflicts.is_empty() {
    for conflict in conflicts.into_iter().collect::<BTreeSet<_>>() {
      println!("{conflict}");
    }
    println!("No project task files or tracking data were changed.");
    return Ok(1);
  }
  if before_bytes.is_none() && next.tasks.is_empty() {
    println!("No installed shared tasks to sync.");
    return Ok(0);
  }
  // Do not rewrite a user-owned lockfile on a semantic no-op, even when it was
  // emitted by the other CLI or has different whitespace/comments.
  if before_bytes.is_none() || serde_json::to_value(&before)? != serde_json::to_value(&next)? {
    changes.push(Change {
      path: ".dotasks-lock.yaml".into(),
      before: before_bytes.as_ref().map(|b| files::hash(b)),
      after: Some(after_bytes),
    });
  }
  let config = files::resolve(&project.root_directory, ".dotasks.yaml")?;
  if action == "--add" && !config.is_file() && !project.task_directory.join("config.yaml").is_file() {
    changes.push(Change {
      path: ".dotasks.yaml".into(),
      before: None,
      after: Some(b"version: 1\nsettings: {}\n".to_vec()),
    });
  }
  if dry {
    println!(
      "Dry run: {} project file change(s); nothing written to the project.",
      changes.len()
    );
  } else {
    transaction.apply(&changes)?;
    println!(
      "{}",
      if changes.is_empty() {
        "Project tasks are up to date."
      } else {
        "Project tasks and tracking updated. Review and commit the changes."
      }
    );
  }
  Ok(0)
}
fn installed(tracking: &Tracking, selections: &[Selection]) -> Result<Vec<String>> {
  let mut ids = BTreeSet::new();
  for s in selections {
    let matches: Vec<_> = tracking
      .tasks
      .keys()
      .filter(|id| {
        id.split_once('/')
          .is_some_and(|(source, task)| source.eq_ignore_ascii_case(&s.source) && s.matches(task))
      })
      .cloned()
      .collect();
    if matches.is_empty() {
      bail!(
        "No installed shared tasks match '{}/{}'. Handwritten/untracked tasks cannot be removed by dotask.",
        s.source,
        s.pattern
      );
    }
    ids.extend(matches);
  }
  Ok(ids.into_iter().collect())
}
fn verify_installed(project: &Directory, task: &Installed, conflicts: &mut Vec<String>) -> Result<()> {
  for (path, hash) in &task.files {
    let path = files::resolve(&project.task_directory, path)?;
    if path.is_dir() || files::hash_file(&path)?.as_ref() != Some(hash) {
      conflicts.push(format!(
        "Refusing to change '{}': the installed shared task is missing or locally modified.",
        path.display()
      ));
    }
  }
  Ok(())
}
fn review_path(store: &Store, project: &Directory, id: &str, revision: &str) -> Result<PathBuf> {
  files::resolve(
    &store.cache,
    &format!(
      ".conflicts/{}/{id}/{revision}",
      &files::hash(project.root_directory.to_string_lossy().as_bytes())[..16]
    ),
  )
}
fn comparison(
  store: &Store,
  project: &Directory,
  root: &Path,
  old: &Installed,
  incoming: &Installed,
  review: &Value,
) -> Result<()> {
  fs::create_dir_all(root)?;
  for path in old.files.keys().chain(incoming.files.keys()).collect::<BTreeSet<_>>() {
    if let Some(hash) = old.files.get(path)
      && store.object(&old.source, hash)?.is_file()
    {
      files::atomic(
        &files::resolve(root, &format!("{path}.base"))?,
        &store.original(&old.source, hash)?,
        true,
      )?;
    }
    let current = files::resolve(&project.task_directory, path)?;
    if current.is_file() {
      files::atomic(&files::resolve(root, &format!("{path}.project"))?, &fs::read(current)?, true)?;
    }
    if let Some(hash) = incoming.files.get(path) {
      files::atomic(
        &files::resolve(root, &format!("{path}.incoming"))?,
        &store.original(&incoming.source, hash)?,
        true,
      )?;
    }
  }
  files::atomic(
    &files::resolve(root, "review.json")?,
    files::dotnet_json(review).as_bytes(),
    true,
  )
}
fn listing(
  store: &Store,
  tasks: &BTreeMap<String, SharedTask>,
  invocation: &Path,
  selected: Option<&str>,
) -> Result<()> {
  let project = Directory::locate_optional(invocation.into(), selected, selected.is_none())?;
  let prefix = project
    .task_directory
    .strip_prefix(&project.root_directory)?
    .to_string_lossy()
    .replace('\\', "/");
  let path = files::resolve(&project.root_directory, ".dotasks-lock.yaml")?;
  let bytes = if path.is_file() {
    Some(fs::read(path)?)
  } else {
    None
  };
  let tracking = Tracking::read(bytes.as_deref(), &prefix)?;
  let width = tasks.keys().map(String::len).max().unwrap_or(4).max(4);
  println!("{:width$}  I  M  Description", "Task");
  for (id, task) in tasks {
    crate::process::check_cancelled()?;
    let source = id.split('/').next().unwrap();
    let installed = tracking.tasks.get(id);
    let present = files::resolve(&project.task_directory, &format!("{id}.cs"))?.is_file();
    let status = if !present {
      "—"
    } else if installed.is_some() {
      "✓"
    } else {
      "?"
    };
    let mut comparison = "—";
    if present {
      let mut paths: BTreeSet<_> = task.files.iter().map(|f| format!("{source}/{}", f.path)).collect();
      if let Some(t) = installed {
        paths.extend(t.files.keys().cloned());
      }
      let mut unknown = false;
      let mut equal = true;
      for p in paths {
        let current = files::hash_file(&files::resolve(&project.task_directory, &p)?)?;
        let cached = if source == "private-tasks" {
          files::resolve(&store.private, &p[source.len() + 1..])?
        } else {
          files::resolve(&store.cache, &p)?
        };
        let cached = files::hash_file(&cached)?;
        unknown |= cached.is_none();
        equal &= cached == current;
      }
      comparison = if unknown {
        "?"
      } else if equal {
        "✓"
      } else {
        "X"
      };
    }
    println!("{id:width$}  {status}  {comparison}  {}", task.description);
  }
  println!("\nI = Installed\nM = Matches cache (private tasks: matches original)\n✓ = Yes; X = Differs; ? = Unknown/untracked; — = Not applicable");
  Ok(())
}
