<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <AssemblyName>dotask-installer</AssemblyName>
    <RootNamespace>DoTask.Installer</RootNamespace>
    <IsPackable>false</IsPackable>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../Dotask/Dotask.csproj" />
  </ItemGroup>
</Project>
